### ISSUE TITLE
FO UV Details

### ISSUE THREAD

**Issue by infinityab** [matthewwall/weewx-wh23xx#3]
I think we have the answer to the FO 'UV' as to what it actually is. Firstly it seems that it has to be multiplied by 1000 to get the true (FO) UV value and the UVI is derived from that based on a standard table. I have crosschecked this against the output and it appears to be correct.
I contacted Alisa Huang from FO in China and they have been helpful and provided some details of their code and calculations relating to UV, attached below.

转发: RE: WH2310 USB output data
[FO-UV.txt](https://github.com/matthewwall/weewx-wh23xx/files/697924/FO-UV.txt)

**Comment by matthewwall** [comment]
thanks for that.  i added the uv-to-uvi conversion to historical records.  also removed the division by 1000.0, so the uv_raw measure should now be in uW/m^2 instead of W/m^2.  fine offset docs say that the raw uv measure is in uW/m^2, but i'm not sure whether that is correct.  the 'radiation' value is still obtained from the luminosity measure.

commit 62737ed (driver version 0.11)

i think we should be seeing values around 98,000 lumens for luminosity and around 750 W/m^2 for radiation for mid-day summertime.
