### ISSUE TITLE
Caught WeeWxIOError: no mapping for id 0x3b

### ISSUE THREAD

**Issue by AmpacheUser** [matthewwall/weewx-wh23xx#6]
I got the following error, and weewx did seem to recover and restart itself but I then noticed some bad Solar Data right after. I have also seen similar errors and then bad rain data.

wh23xx: no mapping for item id 0x3b (0x7b) at index 9 of 01 02 58 02 02 16 03 01 7b 7b 7b 16 05 02 16 06 24 07 22 08 26 43 09 27 d4 0a 00 b4 0b 00 03 0c 00 07 0e 00 00 00 00 10 00 00 00 00 11 00 00 00 15 12 00 00 01 56 13 00 00 01 56 14 00 00 01 56 15 00 00 82 dc 16 00 63 17 01 (len=74)
weewx[32415]: engine: Caught WeeWxIOError: no mapping for id 0x3b
engine: Caught WeeWxIOError: read_record: missing READ_RECORD: 0x3b != 0x04

Also have gotten this error.

wh23xx: no mapping for item id 0x33 (0xb3) at index 25 of 01 02 67 02 01 b4 03 01 a7 04 01 b4 05 01 b4 06 22 07 5b 08 26 22 09 27 b3 b3 00 2d 0b 00 00 0c 00 07 0e 00 00 00 00 10 00 00 00 00 11 00 00 00 15 12 00 00 01 56 13 00 00 01 56 14 00 00 01 56 15 00 00 00 00 16 00 00 17 00 (len=74)
engine: Shutting down StdReport thread
engine: Caught WeeWxIOError: no mapping for id 0x33

This weather station is a POS actually, think I'm going to return it, but figured I'd show this error.

**Comment by matthewwall** [comment]
thank you for posting.

the 'no mapping' typically happens when the data sent by the console is corrupt.  this can be due to a cheap usb cable, radio interference on an unshielded cable, flaky voltage on the usb, or perhaps buggy firmware in the weather station console.

are you running this on a raspberry pi?

the 'missing READ_RECORD' is probably due to data left on the usb buffer after weewx recovered.  weewx should do a usb reset to try and flush the buffer, but i've had mixed experience with that actually working.

could you post the portions of the log where you got bad solar data and bad rain data?

sorry about any instability - i only have some rudimentary documentation (mostly in chinese) to work from, and those docs never tell you about the firmware bugs or timing/protocol quirks.

**Comment by AmpacheUser** [comment]
I'm going to go ahead and try another thicker USB Cable.
I've had the device connected to an openSuse desktop machine and also a laptop running Linux Mint 18.
I will go ahead and run weewx manually now to see the data coming in.
I've also had it just randomly crash (probably not so random, just don't have the logs) and not recover.
I am running monit and having it restart weewx when it stops.
I've found this line from looking at old syslogs:

LOOP:   2017-01-24 01:24:04 MST (1485246244) altimeter: 29.8293095773, appTemp: 46.1581713887, barometer: 29.8591911467, cloudbase: 2944.92071453, dateTime: 1485246244, dewpoint: 41.0011488561, heatindex: 48.56, humidex: 48.56, inDewpoint: 46.3180420495, inHumidity: 41, inTemp: 71.24, luminosity: 0.0, maxSolarRad: None, outHumidity: 75, outTemp: 48.56, pressure: 28.53777992, radiation: 0.0, rain: 0.0, rainRate: 10568325.0394, usUnits: 1, UV: 0, uv_raw: 0, windchill: 48.56, windDir: 225, windGust: 2.23694185194, windSpeed: 0.671082555582

No problem about any instability, I tried using WD for some time, but it would always result in the weathersmart software losing all data/connection to the console and only disconnecting and reconnecting would fix it.

**Comment by matthewwall** [comment]
the station i use for testing had been quite stable.  but your message prompted me to check the logs.  it turns out that i'm seeing a bunch of 'no mapping for item id 0x3b (0xbb)' messages.  too.  this is on a station that is plugged in to a x86_64 machine running debian7 on a battery backup.  the messages started after i made some adjustments to the solar sensor last week.

don't toss your station just yet - i'll see if i can figure out the source/meaning of the 0x3b bytes.  at the very least we can log them and continue instead of causing weewx to reload everything.

**Comment by AmpacheUser** [comment]
Yea, it does recover from the error for me, but it seems then (or maybe before and that what is causing it) I get some crazy Rain, rainRate or w/m2 numbers.

What exactly from the logs are you looking for or that can help you?

**Comment by matthewwall** [comment]
those would be coming from random bytes left on the usb.

there is a checksum in each message, but the driver is ignoring it right now.  you might try setting debug=1 then watch for 'read_record: rbuf: ' messages.  they will have a 'chksum=xxx' at the end.  the xxx should equal the sum of the bytes.

i'll see if i can make the driver ignore any data from messages with mismatched checksum.

**Comment by AmpacheUser** [comment]
I'll try that and keep my eye out for an updated driver to test.

**Comment by matthewwall** [comment]
please try 0.13rc1

this verifies the checksums and does retries for bogus data instead of popping up to weewx for a reload.

i've been running it for awhile now, but of course now my test station is no longer emitting the funky bytes...

**Comment by AmpacheUser** [comment]
Thank you, testing now. I will let you know how it goes

**Comment by AmpacheUser** [comment]
So good news, I changed the USB cable, tried using a different USB port and also now using 0.13rc1. No crashes and no bad data for 24hrs. First time I have been able to go 24hrs with no issues at all.
Thank you!
Update: Now 48hrs running smoothly with no errors or crashes.

**Comment by matthewwall** [comment]
seems to be running well here too.  please open a new issue if you have any problems.
